import uuid
from typing import Dict, List, Optional
from models.story_models import Question, Answer, StorySession
from services.openai_service import OpenAIService
from datetime import datetime

class StoryService:
    def __init__(self):
        self.sessions: Dict[str, StorySession] = {}
        self.openai_service = OpenAIService()
        
        # Dynamic conversation flow - no predefined questions
        self.conversation_flow = {
            "q1": "What was the life-changing moment you experienced?",
            "q2": None,  # Will be generated by GPT based on Q1 answer
            "q3": None,  # Will be generated by GPT based on Q1+Q2 answers
            "q4": None,  # Will be generated by GPT based on Q1+Q2+Q3 answers
        }
        
        # Conversation history for GPT context
        self.conversation_history = {}

    def start_session(self) -> Dict:
        """Start a new story session with dynamic GPT interaction"""
        session_id = str(uuid.uuid4())
        
        # Initialize conversation history
        self.conversation_history[session_id] = []
        
        # Create session with first question
        session = StorySession(
            session_id=session_id,
            created_at=datetime.now(),
            answers=[],
            current_question=1,
            is_complete=False
        )
        
        self.sessions[session_id] = session
        
        return {
            "session_id": session_id,
            "question": self.conversation_flow["q1"],
            "question_id": "q1",
            "message": "I'm here to help you turn a powerful life moment into a visual story. Ready to begin your interview?"
        }

    def submit_answer(self, session_id: str, answer_text: str) -> Dict:
        """Submit an answer and get the next question from GPT"""
        if session_id not in self.sessions:
            return {"error": "Session not found"}
        
        session = self.sessions[session_id]
        current_question_number = session.current_question
        
        if current_question_number > 4:
            return {"error": "All questions completed"}
        
        # Add answer to session
        answer = Answer(
            question_id=current_question_number,
            answer_text=answer_text,
            timestamp=datetime.now()
        )
        session.answers.append(answer)
        
        # Add to conversation history
        self.conversation_history[session_id].append({
            "question": self._get_current_question_text(session_id, current_question_number),
            "answer": answer_text
        })
        
        # Determine next question
        next_question_number = current_question_number + 1
        
        if next_question_number <= 4:
            # Generate next question using GPT based on conversation history
            next_question_data = self._generate_next_question_with_gpt(session_id, next_question_number)
            
            if next_question_data:
                # Update session
                session.current_question = next_question_number
                
                return {
                    "question": next_question_data["question"],
                    "question_id": f"q{next_question_number}",
                    "message": next_question_data["reaction"],
                    "is_complete": False
                }
            else:
                return {"error": "Failed to generate next question from GPT. Please check your OpenAI API credits and try again."}
        else:
            # All questions completed
            session.current_question = 5  # Mark as complete
            session.is_complete = True
            return {
                "message": "Thank you for sharing your story with such openness and courage. I'm honored to have been part of this journey with you.\n\nNow that we have your four answers, I'm going to help you transform them into a visual storyboard — something that could be used for a short video, animated clip, or even a slideshow. This will include suggested scenes, visuals, mood, and transitions to bring your experience to life with meaning and impact.",
                "is_complete": True
            }

    def _get_current_question_text(self, session_id: str, question_number: int) -> str:
        """Get the text of the current question"""
        if question_number == 1:
            return self.conversation_flow["q1"]
        
        # For questions 2-4, we need to get them from conversation history
        # This is a fallback - in practice, questions are generated dynamically
        question_texts = {
            1: "What was the life-changing moment that you'd like to share with me?",
            2: "What led up to that moment?",
            3: "What happened in that moment?",
            4: "How did this moment change you?"
        }
        return question_texts.get(question_number, f"Question {question_number}")

    def _generate_next_question_with_gpt(self, session_id: str, next_question_number: int) -> Optional[Dict]:
        """Generate next question using GPT based on conversation history"""
        try:
            conversation_history = self.conversation_history[session_id]
            
            # Build conversation context for GPT
            conversation_context = self._build_conversation_context(conversation_history)
            
            # Generate question and reaction using GPT
            gpt_response = self.openai_service.generate_next_question(
                conversation_context=conversation_context,
                question_number=next_question_number,
                conversation_history=conversation_history
            )
            
            if gpt_response:
                return {
                    "question": gpt_response["question"],
                    "reaction": gpt_response["reaction"]
                }
            
        except Exception as e:
            print(f"Error generating next question: {e}")
        
        return None

    def _build_conversation_context(self, conversation_history: List[Dict]) -> str:
        """Build conversation context for GPT"""
        context = "Here's our conversation so far:\n\n"
        
        for i, exchange in enumerate(conversation_history, 1):
            context += f"Question {i}: {exchange['question']}\n"
            context += f"Answer {i}: {exchange['answer']}\n\n"
        
        return context

    def get_session(self, session_id: str) -> Optional[StorySession]:
        """Get session by ID"""
        return self.sessions.get(session_id)

    def get_session_summary(self, session_id: str) -> Optional[Dict]:
        """Get session summary for storyboard generation"""
        session = self.get_session(session_id)
        if not session:
            return None
        
        return {
            "session_id": session_id,
            "questions": [self._get_current_question_text(session_id, i+1) for i in range(len(session.answers))],
            "answers": [a.answer_text for a in session.answers],
            "conversation_history": self.conversation_history.get(session_id, [])
        }

    def get_all_answers_for_story_generation(self, session_id: str) -> Optional[List[Dict]]:
        """Get formatted answers for story generation"""
        if session_id not in self.sessions:
            print(f"Session {session_id} not found in sessions")
            return None
        
        session = self.sessions[session_id]
        print(f"Session has {len(session.answers)} answers")
        
        # Format answers with questions for context
        formatted_answers = []
        conversation_history = self.conversation_history.get(session_id, [])
        
        for i, answer in enumerate(session.answers):
            question_text = conversation_history[i]["question"] if i < len(conversation_history) else f"Question {i+1}"
            formatted_answers.append({
                'question': question_text,
                'answer': answer.answer_text,
                'category': f'question_{i+1}',
                'session_id': session_id
            })
        
        print(f"Formatted {len(formatted_answers)} answers for story generation")
        return formatted_answers

    def save_generated_storyboard(self, session_id: str, storyboard: str) -> bool:
        """Save the generated storyboard to the session"""
        if session_id not in self.sessions:
            print(f"Session {session_id} not found")
            return False
        
        session = self.sessions[session_id]
        session.generated_story = storyboard
        print(f"Saved storyboard for session {session_id}")
        return True

    def get_generated_storyboard(self, session_id: str) -> Optional[str]:
        """Get the generated storyboard from the session"""
        if session_id not in self.sessions:
            print(f"Session {session_id} not found")
            return None
        
        session = self.sessions[session_id]
        return session.generated_story

    def save_user_email(self, session_id: str, email: str) -> bool:
        """Save user email to the session"""
        print(f"Attempting to save email {email} for session {session_id}")
        print(f"Available sessions: {list(self.sessions.keys())}")
        
        if session_id not in self.sessions:
            print(f"Session {session_id} not found in sessions")
            return False
        
        session = self.sessions[session_id]
        session.user_email = email
        print(f"Successfully saved email {email} for session {session_id}")
        return True

    def save_to_supabase(self, session_id: str, video_url: str) -> bool:
        """Save the completed story to Supabase"""
        print(f"Attempting to save to Supabase for session {session_id} with video {video_url}")
        print(f"Available sessions: {list(self.sessions.keys())}")
        
        if session_id not in self.sessions:
            print(f"Session {session_id} not found in sessions")
            return False
        
        session = self.sessions[session_id]
        print(f"Session found, user_email: {session.user_email}")
        
        if not session.user_email:
            print(f"No email found for session {session_id}, skipping Supabase save")
            return False
        
        try:
            import os
            from supabase import create_client
            
            # Get Supabase client
            supabase_url = os.getenv('SUPABASE_URL')
            supabase_key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
            
            print(f"Supabase URL: {supabase_url}")
            print(f"Supabase Key: {supabase_key[:10]}..." if supabase_key else "None")
            
            if not supabase_url or not supabase_key:
                print("Supabase credentials not found")
                return False
            
            supabase = create_client(supabase_url, supabase_key)
            
            # Prepare data for Supabase
            data_to_insert = {
                'email': session.user_email,
                'video_url': video_url,
                'created_at': session.created_at.isoformat()
            }
            print(f"Data to insert: {data_to_insert}")
            
            # Save to Supabase
            response = supabase.table('story_submissions').insert([data_to_insert]).execute()
            
            print(f"Supabase response: {response}")
            print(f"Successfully saved story to Supabase for session {session_id}")
            return True
            
        except Exception as e:
            print(f"Error saving to Supabase: {e}")
            return False

    def generate_video_with_videogen_outline(self, session_id: str) -> dict:
        """
        Generate video using VideoGen's Prompt-to-Outline and Outline-to-Video APIs
        
        Returns:
            dict: {
                'success': bool,
                'outline': dict (if successful),
                'api_file_id': str (if successful),
                'error': str (if failed)
            }
        """
        print(f"Generating video with VideoGen outline APIs for session {session_id}")
        
        if session_id not in self.sessions:
            return {'success': False, 'error': 'Session not found'}
        
        session = self.sessions[session_id]
        
        if not session.is_complete:
            return {'success': False, 'error': 'Session is not complete'}
        
        try:
            # Step 1: Create a prompt from the answers
            formatted_answers = [
                {'answer': answer.answer_text if hasattr(answer, 'answer_text') else str(answer)}
                for answer in session.answers
            ]
            
            videogen_prompt = self.openai_service.create_videogen_prompt_from_answers(formatted_answers)
            print(f"Created VideoGen prompt: {videogen_prompt[:200]}...")
            
            # Step 2: Generate outline from prompt
            outline = self.videogen_service.generate_outline_from_prompt(videogen_prompt)
            print(f"Generated outline from VideoGen")
            
            # Save the outline as the "storyboard" for display
            session.generated_story = str(outline)
            
            # Step 3: Generate video from outline
            api_file_id = self.videogen_service.generate_video_from_outline(outline)
            print(f"Generated video from outline, apiFileId: {api_file_id}")
            
            return {
                'success': True,
                'outline': outline,
                'api_file_id': api_file_id
            }
            
        except Exception as e:
            print(f"Error generating video with VideoGen outline: {str(e)}")
            import traceback
            traceback.print_exc()
            return {'success': False, 'error': str(e)}
    
    def clear_session(self, session_id: str) -> bool:
        """Clear session data"""
        if session_id in self.sessions:
            del self.sessions[session_id]
        if session_id in self.conversation_history:
            del self.conversation_history[session_id]
        return True