import uuid
from typing import Dict, List, Optional
from models.story_models import Question, Answer, StorySession
from services.openai_service import OpenAIService
from services.videogen_service import VideoGenService
from datetime import datetime

class StoryService:
    def __init__(self):
        self.sessions: Dict[str, StorySession] = {}
        self.openai_service = OpenAIService()
        self.videogen_service = VideoGenService()
        
        # Dynamic conversation flow - no predefined questions
        self.conversation_flow = {
            "q1": "What was the life-changing moment you experienced?",
            "q2": None,  # Will be generated by GPT based on Q1 answer
            "q3": None,  # Will be generated by GPT based on Q1+Q2 answers
            "q4": None,  # Will be generated by GPT based on Q1+Q2+Q3 answers
        }
        
        # Conversation history for GPT context
        self.conversation_history = {}

    def start_session(self) -> Dict:
        """Start a new story session with dynamic GPT interaction"""
        session_id = str(uuid.uuid4())
        
        # Initialize conversation history
        self.conversation_history[session_id] = []
        
        # Create session with first question
        session = StorySession(
            session_id=session_id,
            created_at=datetime.now(),
            answers=[],
            current_question=1,
            is_complete=False
        )
        
        self.sessions[session_id] = session
        
        return {
            "session_id": session_id,
            "question": self.conversation_flow["q1"],
            "question_id": "q1",
            "message": "I'm here to help you turn a powerful life moment into a visual story. Ready to begin your interview?"
        }

    def submit_answer(self, session_id: str, answer_text: str) -> Dict:
        """Submit an answer and get the next question from GPT"""
        if session_id not in self.sessions:
            return {"error": "Session not found"}
        
        session = self.sessions[session_id]
        current_question_number = session.current_question
        
        if current_question_number > 4:
            return {"error": "All questions completed"}
        
        # Add answer to session
        answer = Answer(
            question_id=current_question_number,
            answer_text=answer_text,
            timestamp=datetime.now()
        )
        session.answers.append(answer)
        
        # Add to conversation history
        self.conversation_history[session_id].append({
            "question": self._get_current_question_text(session_id, current_question_number),
            "answer": answer_text
        })
        
        # Determine next question
        next_question_number = current_question_number + 1
        
        if next_question_number <= 4:
            # Generate next question using GPT based on conversation history
            next_question_data = self._generate_next_question_with_gpt(session_id, next_question_number)
            
            if next_question_data:
                # Update session
                session.current_question = next_question_number
                
                return {
                    "question": next_question_data["question"],
                    "question_id": f"q{next_question_number}",
                    "message": next_question_data["reaction"],
                    "is_complete": False
                }
            else:
                return {"error": "Failed to generate next question from GPT. Please check your OpenAI API credits and try again."}
        else:
            # All questions completed
            session.current_question = 5  # Mark as complete
            session.is_complete = True
            return {
                "message": "Thank you for sharing your story with such openness and courage. I'm honored to have been part of this journey with you.\n\nNow that we have your four answers, I'm going to help you transform them into a visual storyboard — something that could be used for a short video, animated clip, or even a slideshow. This will include suggested scenes, visuals, mood, and transitions to bring your experience to life with meaning and impact.",
                "is_complete": True
            }

    def _get_current_question_text(self, session_id: str, question_number: int) -> str:
        """Get the text of the current question"""
        if question_number == 1:
            return self.conversation_flow["q1"]
        
        # For questions 2-4, we need to get them from conversation history
        # This is a fallback - in practice, questions are generated dynamically
        question_texts = {
            1: "What was the life-changing moment that you'd like to share with me?",
            2: "What led up to that moment?",
            3: "What happened in that moment?",
            4: "How did this moment change you?"
        }
        return question_texts.get(question_number, f"Question {question_number}")

    def _generate_next_question_with_gpt(self, session_id: str, next_question_number: int) -> Optional[Dict]:
        """Generate next question using GPT based on conversation history"""
        try:
            conversation_history = self.conversation_history[session_id]
            
            # Build conversation context for GPT
            conversation_context = self._build_conversation_context(conversation_history)
            
            # Generate question and reaction using GPT
            gpt_response = self.openai_service.generate_next_question(
                conversation_context=conversation_context,
                question_number=next_question_number,
                conversation_history=conversation_history
            )
            
            if gpt_response:
                return {
                    "question": gpt_response["question"],
                    "reaction": gpt_response["reaction"]
                }
            
        except Exception as e:
            print(f"Error generating next question: {e}")
        
        return None

    def _build_conversation_context(self, conversation_history: List[Dict]) -> str:
        """Build conversation context for GPT"""
        context = "Here's our conversation so far:\n\n"
        
        for i, exchange in enumerate(conversation_history, 1):
            context += f"Question {i}: {exchange['question']}\n"
            context += f"Answer {i}: {exchange['answer']}\n\n"
        
        return context

    def get_session(self, session_id: str) -> Optional[StorySession]:
        """Get session by ID"""
        return self.sessions.get(session_id)

    def get_session_summary(self, session_id: str) -> Optional[Dict]:
        """Get session summary for storyboard generation"""
        session = self.get_session(session_id)
        if not session:
            return None
        
        return {
            "session_id": session_id,
            "questions": [self._get_current_question_text(session_id, i+1) for i in range(len(session.answers))],
            "answers": [a.answer_text for a in session.answers],
            "conversation_history": self.conversation_history.get(session_id, [])
        }

    def get_all_answers_for_story_generation(self, session_id: str) -> Optional[List[Dict]]:
        """Get formatted answers for story generation"""
        if session_id not in self.sessions:
            print(f"Session {session_id} not found in sessions")
            return None
        
        session = self.sessions[session_id]
        print(f"Session has {len(session.answers)} answers")
        
        # Format answers with questions for context
        formatted_answers = []
        conversation_history = self.conversation_history.get(session_id, [])
        
        for i, answer in enumerate(session.answers):
            question_text = conversation_history[i]["question"] if i < len(conversation_history) else f"Question {i+1}"
            formatted_answers.append({
                'question': question_text,
                'answer': answer.answer_text,
                'category': f'question_{i+1}',
                'session_id': session_id
            })
        
        print(f"Formatted {len(formatted_answers)} answers for story generation")
        return formatted_answers

    def save_generated_storyboard(self, session_id: str, storyboard: str) -> bool:
        """Save the generated storyboard to the session"""
        if session_id not in self.sessions:
            print(f"Session {session_id} not found")
            return False
        
        session = self.sessions[session_id]
        session.generated_story = storyboard
        print(f"Saved storyboard for session {session_id}")
        return True

    def get_generated_storyboard(self, session_id: str) -> Optional[str]:
        """Get the generated storyboard from the session"""
        if session_id not in self.sessions:
            print(f"Session {session_id} not found")
            return None
        
        session = self.sessions[session_id]
        return session.generated_story

    def save_user_email(self, session_id: str, email: str) -> bool:
        """Save user email to the session"""
        print(f"Attempting to save email {email} for session {session_id}")
        print(f"Available sessions: {list(self.sessions.keys())}")
        
        if session_id not in self.sessions:
            print(f"Session {session_id} not found in sessions")
            return False
        
        session = self.sessions[session_id]
        session.user_email = email
        print(f"Successfully saved email {email} for session {session_id}")
        return True

    def save_to_supabase(self, session_id: str, video_url: str, permanent_url: str = None) -> bool:
        """Save the completed story to Supabase"""
        print(f"Attempting to save to Supabase for session {session_id} with video {video_url}")
        print(f"Available sessions: {list(self.sessions.keys())}")
        
        if session_id not in self.sessions:
            print(f"Session {session_id} not found in sessions")
            return False
        
        session = self.sessions[session_id]
        print(f"Session found, user_email: {session.user_email}")
        
        if not session.user_email:
            print(f"No email found for session {session_id}, skipping Supabase save")
            return False
        
        try:
            import os
            from supabase import create_client
            
            # Get Supabase client
            supabase_url = os.getenv('SUPABASE_URL')
            supabase_key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
            
            print(f"Supabase URL: {supabase_url}")
            print(f"Supabase Key: {supabase_key[:10]}..." if supabase_key else "None")
            
            if not supabase_url or not supabase_key:
                print("Supabase credentials not found")
                return False
            
            supabase = create_client(supabase_url, supabase_key)
            
            # Extract videogen API file ID if present
            videogen_api_file_id = None
            if video_url and video_url.startswith('videogen://'):
                videogen_api_file_id = video_url.replace('videogen://', '')
            
            # Prepare data for Supabase
            data_to_insert = {
                'email': session.user_email,
                'video_url': permanent_url or video_url,
                'videogen_api_file_id': videogen_api_file_id,
                'created_at': session.created_at.isoformat()
            }
            
            # Add permanent_video_url if it's different from video_url
            if permanent_url:
                data_to_insert['permanent_video_url'] = permanent_url
            print(f"Data to insert: {data_to_insert}")
            
            # Save to Supabase
            response = supabase.table('story_submissions').insert([data_to_insert]).execute()
            
            print(f"Supabase response: {response}")
            print(f"Successfully saved story to Supabase for session {session_id}")
            return True
            
        except Exception as e:
            print(f"Error saving to Supabase: {e}")
            return False

    def generate_videogen_outline_for_display(self, session_id: str) -> dict:
        """
        Generate VideoGen outline for display in chat (allows editing before video generation)
        
        Returns:
            dict: {
                'success': bool,
                'outline': dict (if successful),
                'error': str (if failed)
            }
        """
        print(f"Generating VideoGen outline for display for session {session_id}")
        
        if session_id not in self.sessions:
            return {'success': False, 'error': 'Session not found'}
        
        session = self.sessions[session_id]
        
        if not session.is_complete:
            return {'success': False, 'error': 'Session is not complete'}
        
        try:
            # Create a prompt from the answers
            formatted_answers = [
                {'answer': answer.answer_text if hasattr(answer, 'answer_text') else str(answer)}
                for answer in session.answers
            ]
            
            videogen_prompt = self.openai_service.create_videogen_prompt_from_answers(formatted_answers)
            print(f"Created VideoGen prompt for outline")
            
            # Generate outline from prompt
            outline = self.videogen_service.generate_outline_from_prompt(videogen_prompt)
            print(f"Generated outline from VideoGen")
            
            # Store the outline in the session for later video generation
            session.generated_story = str(outline)  # Store as string for compatibility
            
            return {
                'success': True,
                'outline': outline
            }
            
        except Exception as e:
            print(f"Error generating outline for display: {str(e)}")
            import traceback
            traceback.print_exc()
            return {'success': False, 'error': str(e)}
    
    def parse_storyboard_to_outline(self, storyboard_text: str) -> dict:
        """
        Parse edited storyboard text back into VideoGen outline format
        
        Args:
            storyboard_text: The edited storyboard markdown text
            
        Returns:
            dict: VideoGen outline object with sections
        """
        try:
            import re
            
            # Extract all Scene sections using regex
            # Matches: **Scene 1:** followed by text until next **Scene or end
            scene_pattern = r'\*\*Scene\s+\d+:\*\*\s*(.*?)(?=\*\*Scene\s+\d+:|\*\*Tip:|\Z)'
            matches = re.findall(scene_pattern, storyboard_text, re.DOTALL)
            
            sections = []
            for match in matches:
                # Clean up the text - remove extra whitespace and newlines
                text = match.strip()
                if text:
                    sections.append({'text': text})
            
            # If no scenes found, try to extract any text content
            if not sections:
                # Remove all markdown formatting and extract plain text
                lines = storyboard_text.split('\n')
                content_lines = []
                for line in lines:
                    line = line.strip()
                    # Skip markdown headers, tips, and empty lines
                    if line and not line.startswith('**Storyboard:') and not line.startswith('*This is') and not line.startswith('💡'):
                        # Remove markdown formatting
                        line = line.replace('**', '').replace('*', '')
                        content_lines.append(line)
                
                if content_lines:
                    # Combine into sections (split by double newlines if present)
                    full_text = '\n'.join(content_lines)
                    paragraphs = [p.strip() for p in full_text.split('\n\n') if p.strip()]
                    sections = [{'text': p} for p in paragraphs]
            
            # Ensure we have at least one section
            if not sections:
                sections = [{'text': storyboard_text}]
            
            return {'sections': sections}
            
        except Exception as e:
            print(f"Error parsing storyboard: {str(e)}")
            # Fallback: treat entire text as one section
            return {'sections': [{'text': storyboard_text}]}
    
    def _split_text_into_scenes(self, text: str, target_scenes: int = 2) -> list:
        """
        Split a long narrative text into target_scenes distinct scenes based on natural breaks
        
        Args:
            text: Long narrative text
            target_scenes: Number of scenes to create (default: 2)
            
        Returns:
            list: List of scene texts
        """
        import re
        
        # If text is already short (< 150 chars), return as single scene
        if len(text) < 150:
            return [text]
        
        # Strategy: Look for sentence transitions that indicate scene changes
        # Enhanced patterns for better scene detection
        scene_markers = [
            r'\.\s+(But then|Suddenly|Then,|From that moment|That day|After that|Since then|Now)',
            r'\.\s+(I realized|I learned|I understood|I discovered|I felt|I promised)',
            r'\.\s+(Looking back|In hindsight|Today|The reality|Lying there)',
        ]
        
        # Try to find natural breaks
        sentences = re.split(r'(?<=[.!?])\s+', text)
        
        print(f"Total sentences to split: {len(sentences)}")
        
        # Use the provided target_scenes parameter
        sentences_per_scene = max(1, len(sentences) // target_scenes)
        
        print(f"Target scenes: {target_scenes}, sentences per scene: {sentences_per_scene}")
        
        scenes = []
        current_scene = []
        
        for i, sentence in enumerate(sentences):
            current_scene.append(sentence)
            
            # Check if we should start a new scene
            should_break = False
            
            # Check for scene markers in the NEXT sentence (strong indicator)
            if i < len(sentences) - 1:
                next_sentence = sentences[i + 1]
                for pattern in scene_markers:
                    if re.search(pattern, next_sentence):
                        should_break = True
                        print(f"Found scene marker at sentence {i+1}")
                        break
            
            # Or if we've reached target sentences per scene (and we haven't made too many scenes yet)
            if len(current_scene) >= sentences_per_scene and len(scenes) < target_scenes - 1:
                should_break = True
                print(f"Reached sentence limit at sentence {i+1}")
            
            if should_break and current_scene:
                scenes.append(' '.join(current_scene))
                current_scene = []
        
        # Add remaining sentences as last scene
        if current_scene:
            scenes.append(' '.join(current_scene))
        
        print(f"Initial split resulted in {len(scenes)} scenes")
        
        # If we ended up with too few scenes (< 3), force split into more
        if len(scenes) < 3:
            print(f"Too few scenes ({len(scenes)}), forcing split into 4 parts")
            words = text.split()
            chunk_size = len(words) // 4
            scenes = [
                ' '.join(words[:chunk_size]),
                ' '.join(words[chunk_size:chunk_size*2]),
                ' '.join(words[chunk_size*2:chunk_size*3]),
                ' '.join(words[chunk_size*3:])
            ]
        
        final_scenes = [s.strip() for s in scenes if s.strip()]
        print(f"Final scene count: {len(final_scenes)}")
        return final_scenes
    
    def format_outline_as_storyboard(self, outline: dict) -> str:
        """
        Format VideoGen outline as a readable storyboard for display in chat
        
        Args:
            outline: VideoGen outline object with sections
            
        Returns:
            str: Formatted storyboard text with markdown
        """
        try:
            import json
            print(f"=== FORMATTING OUTLINE AS STORYBOARD ===")
            print(f"Outline type: {type(outline)}")
            print(f"Outline keys: {outline.keys() if isinstance(outline, dict) else 'Not a dict'}")
            print(f"Full outline structure: {json.dumps(outline, indent=2)}")
            
            storyboard_parts = []
            storyboard_parts.append("**Storyboard: Your Life-Changing Moment**\n")
            storyboard_parts.append("*This is your story outline generated by VideoGen. You can edit it below before creating your video.*\n")
            
            # Check for different possible structures
            sections = None
            if 'sections' in outline:
                sections = outline['sections']
                print(f"Found 'sections' key with {len(sections)} sections")
            elif 'scenes' in outline:
                sections = outline['scenes']
                print(f"Found 'scenes' key with {len(sections)} scenes")
            elif isinstance(outline, list):
                sections = outline
                print(f"Outline is a list with {len(sections)} items")
            
            if sections:
                print(f"Processing {len(sections)} sections/scenes from VideoGen")
                
                # Show sections as-is from VideoGen (no splitting)
                for i, section in enumerate(sections, 1):
                    print(f"Section {i} keys: {section.keys() if isinstance(section, dict) else 'Not a dict'}")
                    print(f"Section {i} content: {section}")
                    
                    storyboard_parts.append(f"\n**Scene {i}:**")
                    
                    # Extract all relevant content from the section
                    if isinstance(section, dict):
                        # Try different possible field names
                        content_parts = []
                        
                        # Main text/description
                        if 'text' in section:
                            content_parts.append(section['text'])
                        if 'description' in section:
                            content_parts.append(section['description'])
                        if 'narrative' in section:
                            content_parts.append(section['narrative'])
                        if 'textOverlay' in section:
                            content_parts.append(f"Text Overlay: {section['textOverlay']}")
                        if 'voiceover' in section:
                            content_parts.append(f"Voiceover: {section['voiceover']}")
                        
                        # Visual elements
                        if 'visualPrompt' in section:
                            content_parts.append(f"Visual: {section['visualPrompt']}")
                        if 'imagePrompt' in section:
                            content_parts.append(f"Image: {section['imagePrompt']}")
                        
                        # Scene details
                        if 'duration' in section:
                            content_parts.append(f"Duration: {section['duration']}s")
                        
                        if content_parts:
                            storyboard_parts.append(" ".join(content_parts))
                        else:
                            # If no known fields, just stringify the whole section
                            storyboard_parts.append(str(section))
                    else:
                        storyboard_parts.append(str(section))
            else:
                print("WARNING: No sections found in outline!")
                print(f"Outline structure: {outline}")
                # Fallback if structure is different
                storyboard_parts.append("\n" + str(outline))
            
            storyboard_parts.append("\n\n💡 **Tip:** Hover over this message and click the '✏️ Edit' button to modify your storyboard before generating your video!")
            
            result = "\n".join(storyboard_parts)
            print(f"=== FORMATTED STORYBOARD (length: {len(result)}) ===")
            print(result)
            print("=== END STORYBOARD ===")
            return result
            
        except Exception as e:
            print(f"Error formatting outline: {str(e)}")
            import traceback
            traceback.print_exc()
            return f"**Your Story Outline**\n\n{str(outline)}"
    
    def generate_video_with_videogen_outline(self, session_id: str) -> dict:
        """
        Generate video using VideoGen's Prompt-to-Outline and Outline-to-Video APIs
        
        Returns:
            dict: {
                'success': bool,
                'outline': dict (if successful),
                'api_file_id': str (if successful),
                'error': str (if failed)
            }
        """
        print(f"Generating video with VideoGen outline APIs for session {session_id}")
        
        if session_id not in self.sessions:
            return {'success': False, 'error': 'Session not found'}
        
        session = self.sessions[session_id]
        
        if not session.is_complete:
            return {'success': False, 'error': 'Session is not complete'}
        
        try:
            # Check if outline was already generated and stored
            outline = None
            if session.generated_story:
                try:
                    # Try to parse the stored outline
                    import ast
                    outline = ast.literal_eval(session.generated_story)
                    print(f"Using stored outline from session")
                except:
                    print(f"Could not parse stored outline, will regenerate")
                    outline = None
            
            # If no stored outline, generate it now
            if not outline:
                # Step 1: Create a prompt from the answers
                formatted_answers = [
                    {'answer': answer.answer_text if hasattr(answer, 'answer_text') else str(answer)}
                    for answer in session.answers
                ]
                
                videogen_prompt = self.openai_service.create_videogen_prompt_from_answers(formatted_answers)
                print(f"Created VideoGen prompt: {videogen_prompt[:200]}...")
                
                # Step 2: Generate outline from prompt
                outline = self.videogen_service.generate_outline_from_prompt(videogen_prompt)
                print(f"Generated outline from VideoGen")
                
                # Save the outline
                session.generated_story = str(outline)
            
            # Step 3: Generate video from outline
            api_file_id = self.videogen_service.generate_video_from_outline(outline)
            print(f"Generated video from outline, apiFileId: {api_file_id}")
            
            return {
                'success': True,
                'outline': outline,
                'api_file_id': api_file_id
            }
            
        except Exception as e:
            print(f"Error generating video with VideoGen outline: {str(e)}")
            import traceback
            traceback.print_exc()
            return {'success': False, 'error': str(e)}
    
    def clear_session(self, session_id: str) -> bool:
        """Clear session data"""
        if session_id in self.sessions:
            del self.sessions[session_id]
        if session_id in self.conversation_history:
            del self.conversation_history[session_id]
        return True